# ==========================================
#  Default interface fallback values
#  Translations are loaded from JSON files in src/langs/
#  via c.t("UI_*") — these serve as baseline defaults
# ==========================================
from .values import (
    MODE_INSTALL_LOCAL, MODE_INSTALL_OWN, MODE_INSTALL_SHARED, MODE_INSTALL_FLATPAK,
    MODE_BIN_SYSTEM, MODE_BIN_LOCAL, MODE_BIN_CUSTOM, MODE_BIN_FLATPAK,
    STYLE_LIST, STYLE_GRID, STYLE_COLUMNS,
)

UI_SETUP_WIZARD_TITLE = "Asistente de Configuración Inicial"
UI_SETUP_WELCOME_TITLE = "Bienvenidos a CianovaLauncher v{VERSION_LAUNCHER}"
UI_SETUP_WELCOME_SUB = "Gracias por elegir esta herramienta para gestionar tu experiencia en Minecraft Bedrock."
UI_SETUP_LANG_TITLE = "Selecciona tu Idioma"
UI_SETUP_APPEARANCE_TITLE = "Personaliza tu Estilo"
UI_SETUP_LEGAL_TITLE = "Aviso Legal y Términos"
UI_SETUP_LEGAL_CHECK = "He leído y acepto la licencia y los términos de uso"
UI_SETUP_MIGRATION_TITLE = "¿Deseas migrar tus datos?"
UI_SETUP_MIGRATION_SUB = "Si utilizabas MCPETool u otro launcher diferente, puedes traer tus mundos y versiones de forma sencilla."
UI_SETUP_FINISH_TITLE = "Primeros Pasos y Agradecimientos"
UI_SETUP_FINISH_SUB = """¡Muchas gracias por elegir CianovaLauncher v{VERSION_LAUNCHER}!

Este proyecto ha sido desarrollado con dedicación para ofrecerte la mejor experiencia en Linux. Aquí tienes un pequeño resumen de lo que puedes hacer:

<br><br>

🎮 **Pestaña Jugar:** Aquí lanzas tus versiones y gestionas tus **Perfiles Independientes**. Cada perfil guarda sus propios mundos y configuraciones.

<br>

🛠️ **Herramientas:** Instala APKs, descarga desde Google Play, gestiona tus **Texturas, Resource Packs y Behavior Packs** o migra datos de otros launchers.

<br>

⚙️ **Ajustes:** Personaliza el launcher a tu gusto. Puedes cambiar el **Fondo de pantalla**, añadir una **Marca de agua**, ajustar la transparencia y optimizar el rendimiento con Nvidia y Zink.

<br><br>

¡Esperamos que disfrutes de tu aventura en Minecraft!"""
UI_BUTTON_NEXT = "Siguiente"
UI_BUTTON_BACK = "Anterior"
UI_BUTTON_FINISH = "Empezar ahora"
UI_BUTTON_SKIP = "Omitir"
UI_SETUP_THEME_PREVIEW = "Vista previa del estilo:"
UI_SETUP_STEP = "Paso {current} de {total}"
UI_SETUP_RESTART_NOTE = "* El modo claro/oscuro puede requerir reiniciar para aplicarse totalmente."
UI_BUTTON_OPEN_MIGRATION = "Abrir Herramienta de Migración"
UI_SETUP_CHANGELOG_TITLE = "Historial de Cambios"
UI_SETUP_INSTALL_TITLE = "Instalación Inicial"
UI_SETUP_INSTALL_SUB = "Puedes descargar Minecraft ahora o hacerlo más tarde desde la pestaña Herramientas."

# --- Version Dialogs ---
UI_WELCOME_NEW_VERSION_TITLE = "¡Bienvenido a la versión {ver}!"
UI_DOWNGRADE_WARNING_TITLE = "Advertencia de Versión"
UI_DOWNGRADE_WARNING_MSG = "Parece que has usado una versión más reciente ({old}) anteriormente. Se recomienda actualizar a la última versión para evitar conflictos en la configuración."


# --- Flatpak Configuration ---
UI_TITLE_VERSION = "{APP_NAME} - v{VERSION_LAUNCHER}"
UI_TAB_PLAY = " JUGAR "
UI_TAB_TOOLS = " HERRAMIENTAS "
UI_TAB_SETTINGS = " AJUSTES "
UI_TAB_ABOUT = " ACERCA DE "
UI_TAB_LOGS = " LOGS "

# Play Tab
UI_LABEL_SEARCHING = "● Buscando..."
UI_LABEL_INSTALLATION = "Instalación:"
UI_LABEL_INSTALLED_VERSIONS = "Versiones Instaladas"
UI_CHECKBOX_CLOSE_ON_LAUNCH = "Cerrar al jugar"  # legacy
UI_LAUNCH_ACTION_LABEL = "Al lanzar el juego:"
UI_LAUNCH_ACTION_CLOSE = "Cerrar launcher"
UI_LAUNCH_ACTION_HIDE = "Ocultar a la bandeja"
UI_LAUNCH_ACTION_NONE = "No hacer nada"
UI_GAME_STATUS_RUNNING = "▶ En juego"
UI_GAME_STATUS_IDLE = "⏹ Inactivo"
UI_CHECKBOX_GAMEMODE = "Activar GameMode"
UI_BUTTON_PLAY_NOW = "JUGAR AHORA"

# Installation Modes Mapping (Display)
UI_INSTALL_MODES = {
    MODE_INSTALL_LOCAL: "Local",
    MODE_INSTALL_OWN: "Local (Propio)",
    MODE_INSTALL_SHARED: "Local (Compartido)",
    MODE_INSTALL_FLATPAK: "Flatpak (Personalizado)"
}

# Tools Tab
UI_SECTION_INSTALL = "Instalación"
UI_SECTION_CONTENT = "Contenido"
UI_SECTION_CONFIGURATION = "Configuración"
UI_SECTION_SYSTEM = "Sistema"
UI_BUTTON_INSTALL_APK = "Instalar Versión"
UI_BUTTON_MOVE_DELETE_VERSION = "Gestor de Versiones"
UI_BUTTON_VERSION_MANAGER = "Gestor de Versiones"
UI_BUTTON_MIGRATE_DATA = "Migración de Datos"
UI_BUTTON_ADDON_MANAGER = "Gestor de recursos"
UI_BUTTON_SKIN_PACK_CREATOR = "Creador de Skin Packs"
UI_BUTTON_GAME_CONFIG = "Configurador de Juego"
UI_BUTTON_DISABLE_SHADERS = "Desactivar Shaders"
UI_BUTTON_OPEN_DATA_FOLDER = "Abrir Carpeta de Datos"
UI_BUTTON_OPEN_SCREENSHOTS = "Abrir Capturas"
UI_BUTTON_VERIFY_DEPS = "Verificar Dependencias"
UI_BUTTON_VERIFY_HW = "Verificar Requisitos (Hardware)"
UI_LABEL_SHADERS_STATUS = "Shaders: ..."
UI_LABEL_COMPATIBLE_RANGE = "Versiones Compatibles:"
UI_TOOL_DESC_INSTALL_APK = "Instala o añade una versión de Minecraft."
UI_TOOL_DESC_MIGRATE_DATA = "Transfiere datos y mundos desde otro launcher."
UI_TOOL_DESC_VERSION_MANAGER = "Renombra, elimina y crea accesos directos."
UI_TOOL_DESC_ADDON_MANAGER = "Gestiona addons, mods, texturas y packs."
UI_TOOL_DESC_SKIN_PACK_CREATOR = "Crea paquetes de skins personalizados."
UI_TOOL_DESC_OPEN_SCREENSHOTS = "Abre la carpeta de capturas del juego."
UI_TOOL_DESC_GAME_CONFIG = "Edita las opciones y configuración del juego."
UI_TOOL_DESC_DISABLE_SHADERS = "Restablece el modo gráfico del juego."
UI_TOOL_DESC_OPEN_DATA_FOLDER = "Abre la carpeta de datos de los perfiles."
UI_TOOL_DESC_VERIFY_DEPS = "Comprueba las dependencias del sistema."
UI_TOOL_DESC_VERIFY_HW = "Analiza los requisitos de tu hardware."
UI_TOOL_DESC_COMPATIBLE_RANGE = "Rango de versiones soportadas."

# Settings Tab
# --- Settings Categories ---
UI_CATEGORY_GENERAL = "General"
UI_CATEGORY_LAUNCH = "Lanzamiento"
UI_CATEGORY_APPEARANCE = "Apariencia"
UI_CATEGORY_INTEGRATIONS = "Integraciones"
UI_CATEGORY_EXTRAS = "Extras"
UI_SECTION_EXTRAS = "Extras"

UI_SECTION_BINARIES = "Rutas de Binarios"

# Mapeo de Modos de Binarios (Display)
UI_BIN_MODES = {
    MODE_BIN_SYSTEM: "Sistema (Instalado)",
    MODE_BIN_LOCAL: "Local (Junto al script)",
    MODE_BIN_CUSTOM: "Personalizado",
    MODE_BIN_FLATPAK: "Flatpak (Personalizado)"
}

UI_DEFAULT_MODE = MODE_BIN_SYSTEM
UI_LABEL_FLATPAK_ID = "ID de App Flatpak:"
UI_LABEL_BIN_MODE = "Modo de Binarios:"
UI_LABEL_BINARY_PATHS = "Rutas de Binarios"
UI_LABEL_MC_LIBS_PATH = "Carpeta en PATH (mcpelauncher libs):"
UI_LABEL_BIN_FOLDER = "Carpeta de Binarios (auto-resolución):"
UI_BUTTON_AUTO_RESOLVE = "Resolver"
UI_BIN_FOLDER_INVALID = "Selecciona una carpeta de binarios válida."
UI_BIN_AUTO_RESOLVED = "Se detectaron {count} binarios y se asignaron a sus campos."
UI_BIN_AUTO_NONE = "No se encontraron binarios reconocidos en la carpeta."
UI_FOOTER_PROJECT_NAME = "Project CianovaLauncher"
UI_FOOTER_CHANGELOG_TOOLTIP = "Pulsa aquí para ver el changelog"
UI_BUTTON_SAVE_SETTINGS = "Guardar Configuración"
UI_SECTION_APPEARANCE = "Apariencia"
UI_LABEL_COLOR_THEME = "Tema de Color:"
UI_LABEL_APPEARANCE_MODE = "Modo de Apariencia:"
UI_LABEL_LANGUAGE = "Idioma:"
UI_LABEL_VERSION_LIST_STYLE = "Estilo de Lista:"
UI_LABEL_STYLE = "Estilo:"
UI_LABEL_TOOLS_LAYOUT = "Diseño de Herramientas:"
UI_LABEL_ICON_SIZE = "Tamaño de Icono:"
UI_LABEL_TITLE_SIZE = "Tamaño de Título:"
UI_LABEL_CARD_WIDTH = "Anchura de Tarjeta:"
UI_LABEL_CARD_HEIGHT = "Altura de Tarjeta:"

UI_SECTION_BACKGROUND = "Fondo Personalizado"
UI_LABEL_BG_PATH = "Imagen de Fondo:"
UI_LABEL_BG_X = "Posición X:"
UI_LABEL_BG_Y = "Posición Y:"
UI_LABEL_BG_OPACITY = "Opacidad:"
UI_LABEL_BG_ZOOM = "Zoom:"
UI_LABEL_POS_X = "Pos X:"
UI_LABEL_POS_Y = "Pos Y:"
UI_LABEL_COMPATIBLE_RANGE = "Versiones Compatibles:"
UI_BUTTON_RESET_ICON = "Restablecer Icono"

UI_SECTION_STICKER = "Sticker / Watermark"
UI_LABEL_STICKER_MODE = "Modo:"
UI_LABEL_STICKER_CONTENT = "Contenido (Texto/Ruta):"
UI_LABEL_STICKER_CORNER = "Esquina:"
UI_LABEL_STICKER_X = "Distancia X:"
UI_LABEL_STICKER_Y = "Distancia Y:"
UI_LABEL_STICKER_ZOOM = "Zoom Sticker:"
UI_LABEL_STICKER_OPACITY = "Opacidad:"

UI_LABEL_SECTION_OPACITY = "Section Opacity:"

UI_STICKER_MODES = {
    "none": "Desactivado",
    "image": "Imagen (PNG/WebP)",
    "text": "Texto Personalizado"
}

UI_STICKER_CORNERS = {
    "top-left": "Superior Izquierda",
    "top-right": "Superior Derecha",
    "bottom-left": "Inferior Izquierda",
    "bottom-right": "Inferior Derecha"
}

UI_LIST_STYLES = {
    STYLE_LIST: "Lista",
    STYLE_GRID: "Cuadrícula"
}

UI_TOOLS_LAYOUTS = {
    STYLE_COLUMNS: "Dos Columnas",
    STYLE_GRID: "Tarjetas (Cuadrícula)"
}

UI_APPEARANCE_MODES = {
    "Light": "Claro",
    "Dark": "Oscuro",
    "System": "Sistema"
}

UI_COLOR_THEMES = ["blue", "green", "dark-blue", "purple", "orange", "red", "gray", "cyan", "yellow", "midnight", "cherry", "ocean"]

UI_THEME_NAMES = {
    "blue": "Blue",
    "green": "Green",
    "dark-blue": "Dark Blue",
    "purple": "Purple",
    "orange": "Orange",
    "red": "Red",
    "gray": "Gray",
    "cyan": "Cyan",
    "yellow": "Yellow",
    "midnight": "Midnight",
    "cherry": "Cherry",
    "ocean": "Ocean"
}

UI_RESTART_REQUIRED_MSG = "* El cambio de color requiere reiniciar la aplicación."
UI_APPEARANCE_HINT = "Esto solo cambia ligeramente la IU, no la cambia radicalmente."
UI_CONFIRM_TITLE = "Confirmar"
UI_RESTORE_DEFAULTS_CONFIRM = "¿Estás seguro de que quieres restaurar todos los ajustes a sus valores por defecto? La aplicación se cerrará."
UI_RESTORE_DEFAULTS_SUCCESS_TITLE = "Ajustes restaurados"
UI_RESTORE_DEFAULTS_SUCCESS_MSG = "Los ajustes se han restaurado. La aplicación se cerrará ahora."
UI_BUTTON_RESTORE_DEFAULTS = "Restaurar valores"
UI_LABEL_CLIENT_GAME = "Cliente (game):"
UI_LABEL_EXTRACTOR_APK = "Extractor APK:"
UI_LABEL_SIGNIN_UI = "Google Login UI:"
UI_LABEL_GPLAYDL = "Google Play Downloader:"
UI_LABEL_GPLAYVER = "Google Play Version Check:"
UI_LABEL_WEBVIEW_OPTIONAL = "Webview (Opcional):"
UI_LABEL_ERROR_HANDLER_OPTIONAL = "Error Handler (Opcional):"
UI_LABEL_MSA_DAEMON = "MSA Daemon:"
UI_SECTION_COMPATIBILITY = "Compatibilidad"
UI_LOG_VIEWER_LABEL = "Logs:"
UI_LOG_LIVE_SESSION = "Sesión actual"
UI_LOG_PREV_SESSION = "Sesión"
UI_BUTTON_EXPORT_LOG = "Exportar"
UI_EXPORT_LOG_TITLE = "Guardar Log"

# NVIDIA Compatibility
UI_NVIDIA_COMPAT_MODE_CHECKBOX = "Activar modo de compatibilidad para Nvidia (experimental, solo para Flatpak)"
UI_NVIDIA_COMPAT_MODE_TOOLTIP = "Activa esta opción si experimentas crasheos o problemas gráficos con una tarjeta Nvidia. Forza el uso de la GPU dedicada con una capa de compatibilidad (Zink)."
UI_NVIDIA_PRIME_CHECKBOX = "Usar Nvidia Prime (__NV_PRIME_RENDER_OFFLOAD=1)"
UI_NVIDIA_PRIME_TOOLTIP = "Fuerza el uso de la GPU Nvidia en sistemas híbridos (Prime Offloading). Establece __NV_PRIME_RENDER_OFFLOAD, __GLX_VENDOR_LIBRARY_NAME y DRI_PRIME."
UI_ZINK_CHECKBOX = "Usar Driver Zink (MESA_LOADER_DRIVER_OVERRIDE=zink)"
UI_ZINK_TOOLTIP = "Utiliza la capa de compatibilidad Zink para ejecutar OpenGL sobre Vulkan. Recomendado si tienes errores gráficos ('signal 6' o parpadeos) con los drivers nativos de Nvidia en Flatpak."
UI_GAMEMODE_CHECKBOX = "Usar GameMode (gamemoderun)"
UI_GAMEMODE_TOOLTIP = "Optimiza el rendimiento del sistema usando Feral GameMode. Requiere que 'gamemode' esté instalado en el sistema."
UI_CUSTOM_ARGS_CHECKBOX = "Activar Argumentos/Variables Personalizadas"
UI_CUSTOM_ARGS_TOOLTIP = "Permite pasar variables de entorno (KEY=VAL) o argumentos adicionales. Desactiva Nvidia Prime y Zink automáticos."
UI_CUSTOM_ARGS_LABEL = "Argumentos/Variables:"

# Performance / Advanced launch flags
UI_FORCE_OPENGL_CHECKBOX = "Forzar OpenGL (MESA_LOADER_DRIVER_OVERRIDE)"
UI_FORCE_OPENGL_TOOLTIP = "Fuerza el backend de OpenGL para evitar problemas en ciertos drivers gráficos."
UI_FORCE_GLES32_CHECKBOX = "Forzar OpenGL ES 3.2 (MESA_GLES_VERSION_OVERRIDE=3.2)"
UI_FORCE_GLES32_TOOLTIP = "Fuerza el soporte de OpenGL ES 3.2 en versiones de Mesa que lo requieran para Minecraft Bedrock."
UI_DISABLE_VSYNC_CHECKBOX = "Desactivar Vsync (MESA_NO_ERROR=1)"
UI_DISABLE_VSYNC_TOOLTIP = "Desactiva la sincronización vertical o reduce la verificación de errores para mejorar FPS."
UI_FORCE_DISCRETE_GPU_CHECKBOX = "Forzar GPU Discreta (DRI_PRIME=1)"
UI_FORCE_DISCRETE_GPU_TOOLTIP = "Utiliza la segunda tarjeta gráfica disponible (GPU dedicada) en lugar de la integrada."

# --- Discord Rich Presence ---
UI_DISCORD_RPC_SECTION_TITLE = "Discord Rich Presence"
UI_DISCORD_RPC_CHECKBOX = "Activar Discord Rich Presence"
UI_DISCORD_RPC_TOOLTIP = "Muestra en Discord qué versión de Minecraft Bedrock estás jugando con un contador de tiempo. Requiere la librería 'pypresence' instalada y Discord abierto."
UI_CHECKBOX_DISCORD_RPC = "Mostrar en Discord"
UI_DISCORD_RPC_CLIENT_ID_LABEL = "Discord Client ID:"
UI_DISCORD_RPC_MISSING_DEPS = "Discord RPC no disponible: instala 'pypresence' (pip install pypresence)"
UI_DISCORD_RPC_MISSING_CLIENT_ID = "Configura un Discord Client ID en Ajustes > Compatibilidad para activar Rich Presence."

# Dialogs and Messages
UI_INFO_TITLE = "Info"
UI_ERROR_TITLE = "Error"
UI_TITLE_LEGAL = "Términos y Condiciones"
UI_SUCCESS_TITLE = "Éxito"
UI_SAVE_SUCCESS_MSG = "Configuración guardada.\nSe aplicarán los cambios al detectar instalación."
UI_RESTART_REQUIRED_TITLE = "Reinicio Requerido"
UI_RESTART_MSG = "El cambio de color se aplicará completamente al reiniciar la aplicación."
UI_MANAGE_SHORTCUT_TITLE = "Gestionar Accesos Directos"
UI_SHORTCUT_ACTIVE_MSG = "✓ Activo en Menú de Inicio"
UI_SHORTCUT_INACTIVE_MSG = "✗ No instalado en Menú"
UI_CONFIRM_DELETE_SHORTCUT_MSG = "¿Deseas eliminar el acceso directo principal?"
UI_SHORTCUT_DELETED_MSG = "Acceso directo principal eliminado."
UI_SHORTCUT_CREATED_MSG = "Acceso directo '{name}' creado."
UI_CONFIRM_DELETE_TITLE = "Confirmar Eliminación"
UI_SHADER_STATUS_SIMPLE = "0 (Simple)"
UI_SHADER_STATUS_FANCY = "1 (Fancy)"
UI_SHADER_STATUS_VIBRANT = "2 (Vibrant - Activo)"
UI_SHADER_STATUS_UNKNOWN = "Desconocido"
UI_SHORTCUT_CREATION_ERROR_MSG = "No se pudo crear: {e}"
UI_BUTTON_DELETE_MAIN = "Eliminar Principal"
UI_BUTTON_CREATE_MAIN = "Crear Principal"
UI_SECTION_VERSION_SHORTCUTS = "Accesos Directos por Versión"
UI_NO_VERSIONS_INSTALLED = "No hay versiones instaladas"
UI_MANAGE_EXISTING_SHORTCUTS = "Gestionar existentes:"
UI_NO_SHORTCUTS_DETECTED = "(Ninguno detectado)"
UI_BUTTON_CLOSE = "Cerrar"
UI_ERROR_MIGRATION_TOOL = "No se pudo abrir la herramienta: {e}"
UI_MAIN_LAUNCHER_LABEL = "Lanzador Principal"
UI_FLATPAK_SHORTCUT_INFO_TITLE = "Información"
UI_FLATPAK_SHORTCUT_INFO_MSG = "El acceso directo principal de la aplicación Flatpak se crea automáticamente al instalar.\n\nPuedes gestionarlo desde tu tienda de aplicaciones (ej. Discover, GNOME Software)."
UI_SHORTCUT_COMMENT = "Lanzador de Minecraft PE para Linux"
UI_BUTTON_ADD = "Añadir"
UI_BUTTON_DELETE = "Borrar"
UI_CLOSING_FOR_GAME = "Se cerrará el launcher para iniciar el juego..."
UI_CONFIG_ERROR_TITLE = "Error de Configuración"
UI_SELF_LAUNCH_ERROR_MSG = "Se ha detectado un error crítico: El lanzador está intentando ejecutarse a sí mismo en lugar del juego.\n\nPor favor, revisa la configuración de los binarios en la pestaña 'Ajustes' y asegúrate de que la ruta al 'mcpelauncher-client' es correcta."
UI_CRITICAL_LAUNCH_ERROR_TITLE = "Error Crítico de Lanzamiento"
UI_EXECVE_ERROR_MSG = "No se pudo iniciar el juego (execve falló).\nError: {e}"
UI_VERIFYING_TITLE = "Verificando..."
UI_STARTING_MSG = "Iniciando..."
UI_RESULT_TITLE = "Resultado"
UI_VERIFICATION_RESULT_HEADER = "Resultado de Verificación"
UI_ANALYZING_TITLE = "Analizando..."
UI_ANALYZING_HW_MSG = "Analizando Hardware..."
UI_HW_ARCH = "Arquitectura: {arch}\n"
UI_HW_CPU_EXT = "Extensiones CPU: {status}\n"
UI_HW_MODEL = "Modelo"
UI_HW_RAM_TOTAL = "Total"
UI_HW_CPU_INFO = "INFORMACIÓN DE CPU"
UI_HW_RAM_INFO = "INFORMACIÓN DE RAM"
UI_HW_GPU_INFO = "INFORMACIÓN DE GPU"
UI_HW_OPENGL_ES = "OpenGL ES: {gl_ver}\n\n"
UI_SYMLINK_NOT_SUPPORTED_TITLE = "Compatibilidad de Disco"
UI_SYMLINK_NOT_SUPPORTED_MSG = "Los enlaces simbólicos no están soportados en este sistema de archivos (exFAT/NTFS).\n\nEl sistema multiperfil ha sido desactivado por seguridad para evitar pérdida de datos. Se usará el perfil por defecto."
UI_LABEL_UI_SCALE = "Escalado de Interfaz (DPI):"
UI_RESTART_SCALE_MSG = "* El cambio de escalado requiere reiniciar el launcher para aplicarse."
UI_RESTART_LANG_MSG = "El cambio de idioma se aplicará al reiniciar la aplicación."
UI_PROMPT_DESKTOP_SHORTCUT = "¿Deseas agregar también un acceso directo al escritorio?"
UI_VERIFYING_PACKAGES_LABEL = "{title} {count} paquetes..."
UI_INCOMPATIBLE_TEXT = "Incompatible"
UI_VERSION_TEXT = "Versión: "
UI_SHADER_STATUS_LABEL = "Estado Shaders: {status}"
UI_TRAY_SHOW = "Mostrar CianovaLauncher"
UI_TRAY_QUIT = "Salir"
UI_GAME_CONFIG_TITLE = "Configurador de Juego"
UI_TAB_VISUAL = "Interfaz Visual"
UI_TAB_EDITOR = "Editor Manual"
UI_BUTTON_SAVE_FILE = "Guardar Archivo"
UI_SAVE_FILE_SUCCESS = "Archivo guardado correctamente."
UI_ERROR_READING_FILE = "No se pudo leer el archivo: {e}"
UI_ERROR_SAVING_FILE = "No se pudo guardar el archivo: {e}"
UI_FILE_NOT_FOUND_WARN = "El archivo options.txt no existe en esta instalación."

# Game Configuration Labels
UI_GC_GRAPHICS = "Gráficos y Rendimiento"
UI_GC_VIEW_DISTANCE = "Distancia de Renderizado (Chunks)"
UI_GC_MAX_FPS = "Límite de FPS (0 = Ilimitado)"
UI_GC_VSYNC = "Sincronización Vertical (VSync)"
UI_GC_GAMMA = "Brillo (Gamma)"
UI_GC_FULLSCREEN = "Pantalla Completa"
UI_GC_FANCY_SKIES = "Cielos Detallados"
UI_GC_SMOOTH_LIGHTING = "Iluminación Suave"
UI_GC_GRAPHICS_MODE = "Modo de Gráficos"
UI_GC_GRAPHICS_MODE_MAP = ["Simple", "Fancy", "Vibrant Visual"]

UI_GC_GAMEPLAY = "Jugabilidad"
UI_GC_DIFFICULTY = "Dificultad"
UI_GC_DIFFICULTY_MAP = ["Pacífico", "Fácil", "Normal", "Difícil"]
UI_GC_PERSPECTIVE = "Cámara"
UI_GC_PERSPECTIVE_MAP = ["Primera Persona", "Tercera Persona (Detrás)", "Tercera Persona (Frente)"]
UI_GC_LANGUAGE = "Idioma del Juego (ej. es_MX)"

UI_GC_CONTROLS = "Controles"
UI_GC_SENSITIVITY = "Sensibilidad del Ratón"
UI_GC_INVERT_MOUSE = "Invertir Ratón"
UI_GC_AUTO_JUMP = "Salto Automático"
UI_GC_LEFT_HANDED = "Modo Zurdo"
UI_GC_SWAP_JUMP_SNEAK = "Intercambiar Saltar/Agacharse"

UI_GC_AUDIO = "Audio"
UI_GC_SOUND_VOLUME = "Efectos de Sonido"
UI_GC_MUSIC_VOLUME = "Música de Fondo"

UI_GC_PRIVACY = "Privacidad y Red"
UI_GC_SERVER_VISIBLE = "Partida LAN Visible"
UI_GC_XBOX_VISIBLE = "Estado Online (Xbox)"
UI_GC_AUTO_UPDATE = "Actualizaciones Automáticas"
UI_MIGRATION_MANAGER_TITLE = "Gestor de Migración de Datos"
UI_MIGRATION_TITLE = "Migración de Datos"
UI_SOURCE_LABEL = "Origen (Desde donde copiar):"
UI_SOURCE_MODES_DISPLAY = ["Local (.local)", "Flatpak (por ID)", "Personalizado"]
UI_DESTINATION_LABEL = "Destino (Ruta actual):"
UI_WHAT_TO_MIGRATE = "¿Qué deseas migrar?:"
UI_MIGRATE_VERSIONS = "📁 Versiones (versions/)"
UI_MIGRATE_WORLDS = "🌍 Mundos (games/com.mojang/minecraftWorlds/)"
UI_MIGRATE_RESOURCES = "🎨 Paquetes de Recursos (resource_packs/)"
UI_MIGRATE_VERSIONS_SIMPLE = "Versiones"
UI_MIGRATE_WORLDS_SIMPLE = "Mundos"
UI_MIGRATE_RESOURCES_SIMPLE = "Paquetes de Recursos"
UI_MIGRATE_ALL = "📦 Migrar TODO (carpeta completa mcpelauncher/)"
UI_MIGRATION_METHOD = "Método de Migración:"
UI_METHOD_COPY = "Copiar (Mantiene origen y duplica)"
UI_METHOD_MOVE = "Mover (Libera espacio en origen)"
UI_METHOD_LINK = "Enlazar (Symlink - Sincroniza carpetas)"
UI_BUTTON_START_MIGRATION = "🚀 INICIAR MIGRACIÓN"
UI_VALID_FOLDER_DETECTED = "✓ Carpeta válida detectada"
UI_INVALID_FOLDER_WARNING = "⚠ Carpeta no parece contener datos de mcpelauncher"
UI_FOLDER_NOT_EXISTS = "✗ Carpeta no existe"
UI_SELECT_SOURCE_FOLDER = "Seleccionar carpeta de origen"
UI_MIGRATION_CONFIRM_MSG = "¿Estás seguro de migrar datos?\n\nDe: {src}\nA: {dst}\nMétodo: {method}\nElementos: {items}"
UI_MIGRATING_TITLE = "Migrando..."
UI_MIGRATING_MSG = "Copiando archivos, por favor espera..."
UI_MIGRATION_SUCCESS_MSG = "Migración completada.\nElementos procesados: {count}\n\nRefresca para ver cambios."
UI_SKIN_PACK_CREATOR_TITLE = "Creador de Skin Packs"
UI_PACK_NAME_LABEL = "Nombre del Pack:"
UI_SKINS_ADDED_LABEL = "Skins Añadidas"
UI_BUTTON_ADD_SKINS_PNG = "Añadir Skins (PNG)"
UI_BUTTON_EXPORT_MCPACK = "Exportar .mcpack"
UI_ERROR_MISSING_NAME_OR_SKINS = "Falta nombre del pack o skins."
UI_PACK_SAVED_SUCCESS = "Pack guardado en {save_path}"
UI_INSTALL_NEW_VERSION_TITLE = "Instalar Nueva Versión"
UI_INSTALL_TAB_GOOGLE = "Google Play"
UI_INSTALL_TAB_LOCAL = "APK Local"
UI_BUTTON_LOGIN_GOOGLE = "Iniciar Sesión (Google)"
UI_LABEL_SELECT_VERSION = "Seleccionar Versión:"
UI_LABEL_SELECT_ARCH = "Arquitectura:"
UI_LABEL_FILTER_VERSIONS = "Filtrar:"
UI_FILTER_ALL = "Todas"
UI_FILTER_STABLE = "Estables"
UI_FILTER_BETA = "Betas"
UI_LABEL_DOWNLOAD_PROGRESS = "Descargando: {p}%"
UI_STATUS_GETTING_INFO = "Obteniendo información..."
UI_STATUS_DOWNLOADING = "Descargando..."
UI_STATUS_EXTRACTING = "Extrayendo..."
UI_STATUS_LOGIN_REQUIRED = "Inicia sesión para continuar"
UI_STATUS_SESSION_ACTIVE = "✓ Sesión Activa"
UI_STATUS_SESSION_INACTIVE = "✗ Sesión no Iniciada"
UI_STATUS_LOGIN_IN_PROGRESS = "⏳ Ventana de inicio de sesión abierta..."
UI_STATUS_LOGIN_WAITING = "⏳ Esperando token... ({s}s)"

# --- Google Play: Download and Session Errors (shown in UI) ---
UI_GOOGLE_DELIVERY_STATUS_2 = ("Google Play did not deliver this specific version. Common causes:\n"
    "• The selected version is no longer in Google's active catalog\n"
    "  (Google removes old versions and only offers the current release plan).\n"
    "• The account does not own Minecraft Bedrock.\n\n"
    "Solutions:\n"
    "1. Check 'Latest version (auto)' and retry.\n"
    "2. Verify ownership at:\n"
    "   https://play.google.com/store/apps/details?id=com.mojang.minecraftpe\n"
    "3. Use the 'Local APK' tab to install an APK you already have.")
UI_GOOGLE_DELIVERY_STATUS_3 = ("The selected version is not available for this architecture.\n\n"
    "Try changing the architecture (x86_64 / x86) or choose another version.")
UI_GOOGLE_DELIVERY_STATUS_5 = "App not found on Google Play."
UI_GOOGLE_DELIVERY_STATUS_UNKNOWN = "Google Play rejected the download (delivery status={status})."
UI_GOOGLE_SESSION_EXPIRED = ("Your Google session has expired. Close this window, sign in again, "
    "and retry the download.")
UI_GOOGLE_DROIDGUARD_REQUIRED = ("Google requires DroidGuard for this account/device. "
    "Try with a different account or network.")
UI_GOOGLE_DOWNLOAD_ERROR = "Download error (code {code}).\n\ngplaydl output:\n{tail}"
UI_GOOGLE_TOKEN_EXCHANGE_FAILED = ("The Google token could not be exchanged.\n\n"
    "Possible causes:\n"
    "• The session expired before the exchange completed.\n"
    "• Google rejected the authentication (restricted account or no Play access).\n\n"
    "Sign in again without an encryption password and complete the quick flow.")
UI_GOOGLE_SIGNIN_NO_TOKEN = ("The sign-in process finished without delivering a token. "
    "Please try again and complete the flow in the Google window.")
UI_GOOGLE_SIGNIN_LAUNCH_FAILED = "Could not start '{bin_path}'. Check the path in Settings."
UI_GOOGLE_LOGIN_LAUNCH_ERROR = "Failed to launch sign-in: {error}"

UI_VERSION_LATEST_LABEL = "★ Última versión (auto) — recomendado"
UI_APK_FILE_LABEL = "Archivo APK:"
UI_SELECT_APK_PLACEHOLDER = "Selecciona un APK..."
UI_VERSION_NAME_LABEL = "Nombre de la Versión:"
UI_VERSION_NAME_PLACEHOLDER = "Ej: 1.20.50"
UI_INSTALL_MODE_DEST_LABEL = "Modo de Instalación (Destino):"
UI_INSTALL_MODE_OWN = "Local (Flatpak Propio)"
UI_INSTALL_MODE_SHARED = "Local (.local/share)"
UI_INSTALL_MODE_LOCAL = "Local"
UI_INSTALL_MODE_FLATPAK_DESC = "Flatpak (Personalizado)"
UI_FLATPAK_CUSTOM_ID_LABEL = "Flatpak (ID Personalizado):"
UI_BUTTON_INSTALL_NOW = "INSTALAR AHORA"
UI_SELECT_APK_TITLE = "Seleccionar archivo APK"
UI_APK_FILES_TYPE = "Archivos APK"
UI_APK_DROP_HINT = "O arrastra un APK aquí"
UI_ERROR_SELECT_VALID_APK = "Selecciona un APK válido."
UI_ERROR_WRITE_VERSION_NAME = "Escribe un nombre para la versión."
UI_OPEN_FILE_TITLE = "Abrir archivo"
UI_SAVE_FILE_TITLE = "Guardar archivo"
UI_ALL_FILES_TYPE = "Todos los archivos"
UI_SELECT_FOLDER_TITLE = "Seleccionar carpeta"
UI_OPEN_FILES_TITLE = "Abrir archivos"
UI_ARCH_NATIVE = "Compatible ({arch} Nativo)"
UI_ARCH_LEGACY = "Compatible (x86 Legacy)"
UI_ARCH_INCOMPATIBLE = "Incompatible (Solo ARM detectado)"
UI_ARCH_UNKNOWN = "Desconocido (No se detectaron librerías)"
UI_ARCH_POSSIBLY_INCOMPATIBLE = "Posiblemente Incompatible (Sistema: {arch})"
UI_VERSION_NOT_INSTALLED_ERROR = "La versión '{version}' no está instalada."
UI_NO_TARGET_PATH_ERROR = "No se ha definido una ruta de destino."
UI_EXTRACTING_APK_TITLE = "Extrayendo APK"
UI_EXTRACTING_APK_MSG = "Por favor espera, esto puede tardar unos minutos..."
UI_EXTRACTION_SUCCESS_MSG = "Versión {ver_name} instalada correctamente."
UI_EXTRACTION_ERROR_MSG = "El extractor falló:\n{err_msg}"
UI_CRITICAL_ERROR_MSG = "Fallo crítico: {e}"
UI_MANAGE_VERSION_TITLE = "Gestor Avanzado de Versiones"
UI_MANAGE_VERSION_PROMPT = "Gestionar versión: {version}"
UI_BUTTON_RENAME = "Renombrar"
UI_BUTTON_CHANGE_ICON = "Cambiar Icono"
UI_LABEL_ICON_ZOOM = "Zoom Icono:"
UI_MOVE_TO_BACKUP = "Mover a Respaldo"
UI_DELETE_PERMANENTLY = "Eliminar"
UI_VERSION_MOVED_MSG = "Versión movida al respaldo."
UI_CONFIRM_PERMANENT_DELETE = "¿Estás seguro de eliminar PERMANENTELMENTE '{version}'?\nEsta acción no se puede deshacer."
UI_VERSION_DELETED_MSG = "Versión eliminada."
UI_SHADERS_DISABLED_MSG = "Shaders desactivados (Modo 0)."
UI_STATUS_LOCAL_OWN = "● Modo: Local (Datos Propios)"
UI_STATUS_LOCAL_SHARED = "● Modo: Local (Compartido .local)"
UI_STATUS_LOCAL = "● Modo: Local (.local)"
UI_STATUS_FLATPAK_CUSTOM = "● Modo: Flatpak ({flatpak_id})"
UI_STATUS_FLATPAK_NO_DATA = "● Flatpak: Datos no encontrados"
UI_STATUS_LOCAL_NO_VERSIONS = "● Local: Sin versiones"

# --- Sistema de Perfiles ---
UI_LABEL_PROFILE = "Perfil:"
UI_PROFILE_DEFAULT = "default"
UI_BUTTON_MANAGE_PROFILES = "Gestionar Perfiles"
UI_PROFILES_MANAGER_TITLE = "Gestor de Perfiles"
UI_BUTTON_ADD_PROFILE = "Añadir Perfil"
UI_BUTTON_DELETE_PROFILE = "Eliminar Perfil"
UI_BUTTON_RENAME_PROFILE = "Renombrar"
UI_PROFILE_MIGRATION_NOTICE = "Sistema de perfiles activado. Tus datos se han movido al perfil 'default'."
UI_PROFILE_NAME_REQUIRED = "Escribe un nombre para el perfil:"
UI_CONFIRM_DELETE_PROFILE = "¿Estás seguro de que quieres eliminar el perfil '{name}'?"

# --- Gestor de Addons ---
UI_ADDON_MANAGER_TITLE = "Gestor de Addons y Recursos"
UI_SEARCH_PLACEHOLDER = "Buscar por nombre..."
UI_STATUS_ACTIVE = "Activo"
UI_STATUS_DISABLED = "Desactivado"
UI_BUTTON_ACTIVATE = "Activar"
UI_BUTTON_DEACTIVATE = "Desactivar"
UI_BUTTON_IMPORT_FILE = "Importar archivo"
UI_TAB_WORLDS = "Mundos"
UI_TAB_BP = "Behavior Packs (BP)"
UI_TAB_RP = "Resource Packs (RP)"
UI_TAB_MCPE_MODS = "Mods MCPELauncher"
UI_TYPE_RESOURCE = "Recursos"
UI_TYPE_BEHAVIOR = "Comportamiento"
UI_TYPE_WORLD = "Mundo"
UI_TYPE_SKIN = "Skins"
UI_TYPE_SKINPACK = "Skinpack"
UI_SCANNING_RESOURCES = "Escaneando recursos..."
UI_TOGGLING_STATUS = "Cambiando estado..."
UI_DELETING_RESOURCE = "Eliminando recurso..."
UI_WORLD_EXPORTED_SUCCESS = "Mundo exportado a: {path}"
UI_INSTALLING_PACK = "Instalando pack..."
UI_PACK_INSTALLED = "Pack instalado correctamente."
UI_INVALID_MANIFEST = "Manifest inválido o no encontrado."
UI_SELECT_PACK_TYPE = "Selecciona el tipo de pack:"
UI_BUTTON_EXPORT = "Exportar"
UI_YES = "Sí"
UI_NO = "No"
UI_CANCEL = "Cancelar"
UI_ERROR_SAME_FOLDER = "Error: La carpeta de origen y destino son la misma"
UI_ERROR_NOTHING_SELECTED = "Nada seleccionado para migrar"
UI_ERROR_FLATPAK_SPAWN_NOT_FOUND = "Error: 'flatpak-spawn' no encontrado. No se puede abrir un terminal externo."
UI_HW_NOT_DETECTED = "No detectado"
UI_LABEL_APP_ID = "App ID:"
UI_PLACEHOLDER_SOURCE_PATH = "Ruta de origen..."
UI_BUTTON_BROWSE_FOLDER = "Buscar Carpeta"
UI_ERROR_READING_APK = "Error leyendo APK: {e}"
UI_APK_COMPATIBLE_X86 = "La APK es compatible (x86) o (x86_64)"
UI_APK_INCOMPATIBLE_ARM = "Esta APK no es compatible (Esta es una APK ARM y necesita una x86)"
UI_APK_INVALID = "La APK esta incompleta o no es de Minecraft"
UI_SKIN_PACK_FILES_TYPE = "Archivos de Skin Pack"
UI_MCPACK_FILES_TYPE = "Archivos Minecraft Pack"
UI_BUTTON_VERIFY_DEPS_FLATPAK = "Verificar Dependencias [Flatpak]"
UI_BUTTON_VERIFY_DEPS_LOCAL = "Verificar Dependencias [Local]"
UI_CONFIG_FLATPAK_CUSTOM_TITLE = "Configurar Flatpak Personalizado"
UI_FLATPAK_ID_LABEL = "ID de Aplicación Flatpak:"
UI_FLATPAK_ID_EXAMPLE = "Ejemplo: org.mcpelauncher.Other"
UI_FLATPAK_ID_REQUIRED_MSG = "Por favor ingresa un ID válido."
UI_BUTTON_USE_ID = "Usar ID"
UI_DATA_DETECTED_TITLE = "Datos Detectados"
UI_MIGRATION_PROMPT_MSG = "Se detectaron datos de una instalación anterior en .local.\nPuedes importarlos desde la pestaña 'Herramientas' > 'Migración de Datos'."
UI_NO_VERSIONS_FOLDER_MSG = "No se encontró la carpeta 'versions'"
UI_ERROR_LISTING_VERSIONS = "Error al listar versiones: {e}"
UI_PLEASE_SELECT_VERSION_MSG = "Por favor selecciona una versión."
UI_CLIENT_PATH_ERROR = "Ruta de Cliente no configurada o inválida."
UI_LOCAL_BINARY_NOT_FOUND = "No se encontró el binario local en: {local_bin}"
UI_SYSTEM_BINARY_NOT_FOUND = "No se encontró mcpelauncher-client en el sistema."
UI_LAUNCH_ERROR = "Fallo al lanzar: {e}"
UI_DETECTED_LABEL = "Detectado: {version}"
UI_NO_WORLDS_FOUND = "No se encontraron mundos."
UI_EXPORT_WORLDS_TITLE = "Exportar Mundos"
UI_SELECT_WORLDS_LABEL = "Selecciona Mundos"
UI_SELECT_DEST_FOLDER_TITLE = "Selecciona carpeta de destino"
UI_WORLDS_EXPORTED_SUCCESS = "{count} mundos exportados a {dest_dir}"
UI_BUTTON_SELECT_ALL = "Seleccionar Todo"
UI_BUTTON_EXPORT_SELECTED = "Exportar Seleccionados"
UI_SCREENSHOTS_NOT_FOUND_MSG = "No se encontró la carpeta específica 'Screenshots'."
UI_OPEN_COMOJANG_FOLDER_PROMPT = "{msg}\n\n¿Quieres abrir la carpeta 'com.mojang' para buscarla manualmente?"
UI_CANNOT_OPEN_FOLDER_ERROR = "No se pudo abrir la carpeta: {e}"
UI_FLATPAK_RUNTIME_INFO_TITLE = "Requisitos de Runtime Flatpak"
UI_FLATPAK_RUNTIME_INFO_TEXT = """
El lanzador se ejecuta en Flatpak. Las dependencias son manejadas
por el entorno de ejecución (runtime).

Asegúrate de tener instalados los runtimes necesarios.

Para Usuarios:
- org.kde.Platform//6.10
- io.qt.qtwebengine.BaseApp

Para Desarrolladores:
- org.kde.Sdk//6.10
"""
UI_DEPENDENCY_CHECK_ERROR = "No se encontró '{list_file}'"
UI_PKG_MANAGER_NOT_SUPPORTED = "Gestor de paquetes no soportado."
UI_DEPENDENCY_LIST_READ_ERROR = "Error leyendo lista: {e}"
UI_MISSING_DEPS_TITLE = "Faltan Dependencias"
UI_MISSING_DEPS_MSG = "❌ Paquetes Faltantes"
UI_INSTALL_PROMPT = "Se intentará ejecutar:\n{full_cmd}\n\n¿Continuar?"
UI_BUTTON_INSTALL_ROOT = "Instalar (Root)"
UI_HARDWARE_ANALYSIS_TITLE = "Verificador de Requisitos"
UI_HARDWARE_ANALYSIS_HEADER = "Análisis de Hardware"
UI_HARDWARE_ANALYSIS_RECOMMENDATION = "VERSIÓN RECOMENDADA MCPE:\n{compat_ver}"
UI_DEPENDENCIES_OK = "✅ Requisitos instalados correctamente."
UI_DEPENDENCIES_FLATPAK_OK = "✅ Flatpak detectado correctamente.\nID: {flatpak_id}"
UI_FLATPAK_APP_NOT_FOUND = "La aplicación Flatpak '{flatpak_id}' no parece estar instalada."
UI_FLATPAK_VERIFICATION_ERROR = "Error verificando Flatpak:\n{e}"
UI_SECTION_FLATPAK_RUNTIMES = "Gestión de Runtimes (Flatpak)"
UI_BUTTON_UPDATE_RUNTIMES = "Actualizar Runtimes Requeridos"

# Migration Wizard UI Strings
UI_WIZARD_STEP_SOURCE_TITLE = "Selecciona el origen"
UI_WIZARD_SOURCE_LOCAL_DESC = "Para usuarios que vengan de CCMC Launcher, MCPETools o instalaciones con datos almacenados en local compartido"
UI_WIZARD_SOURCE_FLATPAK_DESC = "Para usuarios que vengan de un launcher Flatpak, incluido el Oficial o similares"
UI_WIZARD_SOURCE_CUSTOM_DESC = "Selecciona manualmente la carpeta de origen"
UI_WIZARD_SOURCE_CUSTOM_PLACEHOLDER = "Selecciona o escribe la ruta de la carpeta de origen..."

UI_WIZARD_STEP_PROFILE_TITLE = "Selecciona el perfil destino"
UI_WIZARD_PROFILE_DEFAULT_ONLY = "Solo existe el perfil Default. Los datos se guardarán ahí."

UI_WIZARD_STEP_CONTENT_TITLE = "¿Qué deseas migrar?"
UI_WIZARD_CONTENT_ALL_DESC = "Migra todas las versiones, mundos y recursos sin personalizar"
UI_WIZARD_CONTENT_CUSTOM = "Personalizado"
UI_WIZARD_CONTENT_CUSTOM_DESC = "Elige manualmente qué elementos migrar"

UI_WIZARD_STEP_METHOD_TITLE = "Elige el método de migración"
UI_WIZARD_METHOD_SUB = "Selecciona una opción para continuar:"
UI_WIZARD_METHOD_COPY_TITLE = "Copiar (Duplicar)"
UI_WIZARD_METHOD_COPY_DESC = "Copia los datos al nuevo destino sin modificar el origen. Ocupa el doble de espacio pero conserva todo intacto por si algo sale mal."
UI_WIZARD_METHOD_MOVE_TITLE = "Mover (Trasladar)"
UI_WIZARD_METHOD_MOVE_DESC = "Mueve los datos completamente al nuevo destino. Los archivos originales se eliminan. Recomendado si ya no usarás el launcher anterior."
UI_WIZARD_METHOD_LINK_TITLE = "Symlink (Sincronizar)"
UI_WIZARD_METHOD_LINK_DESC = "Crea un enlace simbólico entre origen y destino. Los datos permanecen en su ubicación original y se reflejan en el launcher. Ideal para conservar espacio en disco."

UI_WIZARD_STEP_SUMMARY_TITLE = "Resumen de migración"
UI_WIZARD_SUMMARY_LABEL_SOURCE = "Origen"
UI_WIZARD_SUMMARY_LABEL_DEST = "Destino"
UI_WIZARD_SUMMARY_LABEL_PROFILE = "Perfil"
UI_WIZARD_SUMMARY_LABEL_ITEMS = "Elementos"
UI_WIZARD_SUMMARY_LABEL_METHOD = "Método"
UI_BUTTON_MIGRATE = "🚀 Migrar"

# ── Mods / DRM ──
UI_SECTION_MODS = "Mods"
UI_DRM_MOD_TITLE = "Mod DRM (mcpelauncher-updates)"
UI_DRM_MOD_STATUS_INSTALLED = "✓ Instalado"
UI_DRM_MOD_STATUS_DISABLED = "⚠ Desactivado"
UI_DRM_MOD_STATUS_MISSING = "✗ No instalado"
UI_DRM_MOD_DESC = "Necesario para versiones recientes de Minecraft Bedrock (≥ 1.21.30). Parchea Pairip Core DRM, libPlayFabMultiplayer y libmaesdk.\nCompilado desde github.com/Leimsoto/mcpelauncher-updates (MIT)."
UI_DRM_MOD_CREDIT = "Compilado desde github.com/Leimsoto/mcpelauncher-updates"
UI_BUTTON_INSTALL_DRM_MOD = "Descargar e Instalar Mod DRM"
UI_BUTTON_OPEN_MODS_FOLDER = "Abrir Carpeta de Mods"
UI_BUTTON_OPEN_RESOURCE_MANAGER = "Gestor de Recursos"
UI_BUTTON_OPEN_FOLDER = "📂 Abrir carpeta"
UI_DOWNLOADING_TITLE = "Descargando..."
UI_DOWNLOADING_MSG = "Descargando Mod DRM desde:"
UI_DOWNLOAD_ERROR = "Error de descarga"
UI_DOWNLOAD_EMPTY = "El archivo descargado está vacío"
UI_DRM_INSTALL_SUCCESS = "Mod DRM instalado correctamente en:\n{path}"
UI_DRM_INSTALL_ERROR_MSG = "No se pudo instalar el Mod DRM:\n{error}\n\nSi el problema persiste, descárgalo manualmente desde:\nhttps://github.com/Leimsoto/mcpelauncher-updates/releases"
UI_DRM_ALERT_TITLE = "Mod DRM Requerido"
UI_DRM_ALERT_MSG = "La versión {version} de Minecraft Bedrock requiere el mod DRM (mcpelauncher-updates) para funcionar correctamente.\n\nPuedes descargarlo desde Herramientas > Mods."
UI_DRM_REQUIRED_TITLE = "Mod DRM Necesario"
UI_DRM_REQUIRED_MSG = "La versión {version} fue instalada desde Google Play y requiere el mod DRM (mcpelauncher-updates) para ejecutarse.\n\n¿Deseas instalarlo ahora?"
UI_DRM_DISABLED_TITLE = "Mod DRM Desactivado"
UI_DRM_DISABLED_MSG = "La versión {version} fue instalada desde Google Play, pero el mod DRM está desactivado.\n\nActívalo desde Gestor de Recursos > Mods."
UI_DRM_NO_MODS_FOLDER = "La carpeta de mods no existe para la instalación actual."
UI_MOD_LAUNCH_CHECK = "Cargar al inicio"
UI_AVAILABLE_MODS_HEADER = "Mods disponibles"
UI_MOD_NOT_INSTALLED = "No instalado"
UI_BUTTON_INSTALL_MOD = "Instalar"

# ── Update checker ──
UI_UPDATE_AVAILABLE = "Versión {version} disponible. Actualiza CianovaLauncher para obtener las novedades."
UI_HOTFIX_TITLE = "Actualización crítica disponible"
UI_HOTFIX_MSG = "Hay una corrección urgente disponible para tu versión:\n\n{body}\n\nActualiza CianovaLauncher para aplicarla."
UI_HOTFIX_UPDATE = "Actualizar"
UI_HOTFIX_IGNORE = "Ignorar"

# ── Play Button and Dynamic UI ──
UI_PLAY_BUTTON = "JUGAR"
UI_INSTALL_VIEW_TITLE = "INSTALACIÓN DE VERSIONES DE MINECRAFT"
UI_INSTALL_VIEW_SUBTITLE = "Elige la fuente de instalación: descarga directa desde tu cuenta de Google Play o selecciona un archivo APK local."

# ── Terms and Conditions ──
UI_TERMS_TITLE = "Términos y Condiciones"
UI_TERMS_SUBTITLE = "Por favor, lee cuidadosamente la siguiente información antes de usar CianovaLauncher."
UI_TERMS_DATE = "Act. 4 de julio de 2026"
UI_TERMS_VIEW_DOC = "📄  Ver Documento ↗"

# ── Tools Tab ──
UI_TOOL_TITLE_MIGRATE = "Migrar Datos"
UI_TOOL_DESC_MIGRATE = "Transfiere tus mundos, packs y configuraciones desde otro launcher."
UI_TOOL_BTN_MIGRATE = "Migrar Datos"
UI_TOOL_TITLE_SKIN = "Creador de Skin Packs"
UI_TOOL_DESC_SKIN = "Crea y personaliza tus propios paquetes de skins para Bedrock."
UI_TOOL_BTN_SKIN = "Crear Skin Pack"
UI_TOOL_TITLE_GAME_CONFIG = "Configuración del Juego"
UI_TOOL_DESC_GAME_CONFIG = "Edita las opciones y configuración del launcher y del juego."
UI_TOOL_BTN_GAME_CONFIG = "Configurar"
UI_TOOL_TITLE_SHADERS = "Desactivar Shaders"
UI_TOOL_DESC_SHADERS = "Restaura el modo gráfico del juego a su estado original."
UI_TOOL_BTN_SHADERS = "Desactivar Shaders"
UI_TOOL_TITLE_DATA_FOLDER = "Carpeta de Datos"
UI_TOOL_DESC_DATA_FOLDER = "Accede rápidamente a la carpeta de mundos, configuraciones y más."
UI_TOOL_BTN_DATA_FOLDER = "Abrir Carpeta"
UI_TOOL_TITLE_DEPS = "Verificar Dependencias"
UI_TOOL_DESC_DEPS = "Comprueba que todos los componentes necesarios estén instalados."
UI_TOOL_BTN_DEPS = "Verificar Ahora"
UI_TOOL_TITLE_HARDWARE = "Analizar Hardware"
UI_TOOL_DESC_HARDWARE = "Analiza tu equipo para asegurar un mejor rendimiento."
UI_TOOL_BTN_HARDWARE = "Analizar Hardware"
UI_TOOL_TITLE_COMPAT = "Versiones Compatibles"
UI_TOOL_DESC_COMPAT = "Consulta qué versiones de Minecraft Bedrock son compatibles con tu sistema."
UI_TOOL_BTN_COMPAT = "Ver Versiones"
UI_TOOL_STATUS_SHADERS_DETECTING = "Shaders: Detectando..."
UI_TOOL_STATUS_SHADERS_RESTORED = "Shaders: Modo Original"
UI_TOOL_STATUS_SHADERS_ACTIVE = "Shaders: Activos"

# ── Compatible Versions Dialog ──
UI_COMPAT_TITLE = "Versiones Compatibles de Minecraft Bedrock"
UI_COMPAT_SUBTITLE = "Consulta el soporte por versiones y los requisitos técnicos según tu hardware."
UI_COMPAT_HW_DIAG = "DIAGNÓSTICO DE TU SISTEMA"
UI_COMPAT_CPU_ARCH = "Arquitectura CPU:"
UI_COMPAT_GL_PROFILE = "Perfil Gráfico:"
UI_COMPAT_BTN_ANALYZE_HW = "Analizar Hardware en Detalle"
UI_COMPAT_BTN_UNDERSTOOD = "Entendido"
UI_COMPAT_ARCH_LABEL = "Arquitectura"
UI_COMPAT_EXT_LEGACY = "Arquitectura heredada"
UI_COMPAT_EXT_NEON_FAIL = "Sin soporte NEON"
UI_COMPAT_EXT_NEON_OK = "NEON (Óptimo)"
UI_COMPAT_EXT_SSE_FAIL = "Faltan instrucciones SSE4.2"
UI_COMPAT_EXT_SSE_OK = "SSE4.2 + POPCNT (Óptimo)"
UI_COMPAT_MOTOR_LABEL = "Motor"
UI_COMPAT_RANGE_LABEL = "● Rango: {range}"
UI_COMPAT_TIER1_TITLE = "Minecraft Bedrock 1.20.0 – 1.21.x+ (Era Actual)"
UI_COMPAT_TIER1_STATUS = "Totalmente Compatible"
UI_COMPAT_TIER1_DESC = "Versiones modernas con soporte oficial de Xbox Live, shaders diferidos (Deferred Technical Preview) y servidores. Requiere instrucciones SSE4.2 en x86_64 o NEON en ARM."
UI_COMPAT_TIER2_TITLE = "Minecraft Bedrock 1.18.30 – 1.19.80 (Caves & Cliffs II / The Wild)"
UI_COMPAT_TIER2_STATUS = "Compatible"
UI_COMPAT_TIER2_DESC = "A partir de la versión 1.18.30, Mojang eliminó el soporte para binarios Android de 32 bits. Es indispensable utilizar APKs compilados para arm64-v8a o x86_64."
UI_COMPAT_TIER3_TITLE = "Minecraft Bedrock 1.16.0 – 1.18.12 (Nether Update & Caves I)"
UI_COMPAT_TIER3_STATUS = "Alta Compatibilidad"
UI_COMPAT_TIER3_DESC = "Generación muy estable que soporta tanto arquitecturas de 32 bits (i686 / armv7l) como 64 bits. Ideal para equipos con tarjetas gráficas antiguas o controladores modestos."
UI_COMPAT_TIER4_TITLE = "Minecraft Bedrock 1.13.0 – 1.14.60 (Village & Pillage / Buzzy Bees)"
UI_COMPAT_TIER4_STATUS = "Compatible Clásico"
UI_COMPAT_TIER4_DESC = "Versiones clásicas diseñadas sobre el motor gráfico OpenGL ES 2.0 / 3.0 anterior a RenderDragon. Compatible con prácticamente cualquier GPU moderna o integrada."
UI_COMPAT_LICENSE_TITLE = "Licencia y Adquisición de Versiones"
UI_COMPAT_LICENSE_DESC = "Para poder ejecutar cualquier versión de Minecraft Bedrock en Cianova Launcher, debes haber adquirido el juego en Google Play Store con tu cuenta o proporcionar el paquete de instalación oficial (APK x86_64 / arm64) correspondiente a la versión deseada."

# ── Dependencies Dialog ──
UI_DEPS_DIALOG_TITLE = "Verificación de Dependencias y Sistema"
UI_DEPS_DIALOG_SUBTITLE = "Comprobación verídica de librerías dinámicas, gráficos, audio y herramientas requeridas."
UI_DEPS_TAB_DIAG = "🔍 Diagnóstico en Tiempo Real"
UI_DEPS_TAB_GUIDE = "📖 Guía de Paquetes y Requisitos"
UI_DEPS_STATUS_ALL_OK = "Todo Operativo"
UI_DEPS_STATUS_MISSING = "Dependencias Faltantes"
UI_DEPS_SUMMARY_ALL_OK = "¡Excelente! Tu sistema cuenta con todas las librerías dinámicas y subsistemas requeridos para ejecutar Minecraft Bedrock."
UI_DEPS_SUMMARY_MISSING = "Se detectaron dependencias o librerías faltantes. Consulta la pestaña 'Guía de Paquetes' para ver el comando de instalación para tu distribución."
UI_DEPS_CHECK_ERROR = "Error al verificar dependencias: {error}"
UI_DEPS_ENV_NATIVE = "Entorno: Nativo Linux ({arch})"
UI_DEPS_ENV_FLATPAK = "Entorno: Sandbox Flatpak (Runtimes incluidos)"
UI_DEPS_FOUND = "Librería encontrada: {name}"
UI_DEPS_NOT_FOUND = "No encontrada en el sistema"
UI_DEPS_OPTIONAL = "Opcional"
UI_DEPS_STATUS_CHECKING = "Analizando..."
UI_DEPS_TOOL_FOUND = "Herramienta disponible: {path}"
UI_DEPS_TOOL_NOT_FOUND = "No instalada (opcional pero recomendada)"
UI_DEPS_BTN_RESCAN = "Volver a Analizar"
UI_DEPS_BTN_CLOSE = "Cerrar"
UI_DEPS_BTN_COPY = "Copiar"
UI_DEPS_COPIED_TITLE = "Copiado"
UI_DEPS_COPIED_MSG = "Comando copiado al portapapeles."
UI_DEPS_CAT_GRAPHICS = "GRÁFICOS Y RENDERIZADO"
UI_DEPS_CAT_AUDIO = "AUDIO Y SUBSISTEMA DE SONIDO"
UI_DEPS_CAT_SECURITY = "SEGURIDAD, RED Y CRIPTOGRAFÍA"
UI_DEPS_CAT_COMPRESSION = "COMPRESIÓN Y FORMATOS"
UI_DEPS_CAT_INPUT = "ENTRADA Y DISPOSITIVOS"
UI_DEPS_CAT_TOOLS = "HERRAMIENTAS AUXILIARES Y OPTIMIZACIÓN"
UI_DEPS_ITEM_OPENGL_DESC = "Biblioteca principal de renderizado acelerado por hardware."
UI_DEPS_ITEM_EGL_DESC = "Interfaz nativa de contexto gráfico para Bedrock."
UI_DEPS_ITEM_VULKAN_DESC = "Soporte para shaders modernos y RenderDragon Vulkan."
UI_DEPS_ITEM_ALSA_DESC = "Arquitectura de sonido básica del kernel Linux."
UI_DEPS_ITEM_PULSE_DESC = "Servidor de audio de escritorio moderno."
UI_DEPS_ITEM_CRYPTO_DESC = "Cifrado y autenticación segura para servidores y Xbox Live."
UI_DEPS_ITEM_SSL_DESC = "Capas TLS/SSL para conexiones HTTPS y descarga de paquetes."
UI_DEPS_ITEM_ZLIB_DESC = "Descompresión rápida de recursos y paquetes mundiales."
UI_DEPS_ITEM_PNG_DESC = "Decodificación de texturas e imágenes PNG."
UI_DEPS_ITEM_EVDEV_DESC = "Detección plug-and-play de mandos de juego y periféricos."
UI_DEPS_ITEM_UNZIP_DESC = "Extracción de paquetes APK y addons mcpack/mcworld."
UI_DEPS_ITEM_ZENITY_DESC = "Selector de archivos y avisos del sistema en escritorios Linux."
UI_DEPS_ITEM_GAMEMODE_DESC = "Optimizador de prioridad de CPU y reloj GPU para juegos."
UI_DEPS_DISTRO_UBUNTU_NOTES = "En Debian o derivados con repositorios restringidos, asegúrate de tener activada la sección main."
UI_DEPS_DISTRO_ARCH_NOTES = "Arch proporciona las versiones más recientes y unificadas de las librerías dinámicas."
UI_DEPS_DISTRO_FEDORA_NOTES = "En Fedora los controladores propietarios (como NVIDIA) pueden requerir habilitar RPM Fusion."
UI_DEPS_DISTRO_FLATPAK_TITLE = "Instalación en Contenedor Flatpak"
UI_DEPS_DISTRO_FLATPAK_NOTES = "Si utilizas la versión Flatpak de Cianova Launcher, todas las librerías dinámicas vienen aisladas y auto-contenidas en el runtime. No necesitas instalar paquetes de sistema en tu host."


# ── About Hero Card & Terms Dialog ──
UI_HERO_SUB = "Minecraft Bedrock en Linux"
UI_HERO_MOTTO = "Una herramienta de la comunidad, para la comunidad."
UI_HERO_BADGE_OPEN_TITLE = "Código Abierto"
UI_HERO_BADGE_OPEN_SUB = "GNU GPL v3.0"
UI_HERO_BADGE_COMM_TITLE = "Comunidad"
UI_HERO_BADGE_COMM_SUB = "Hecho por y para usuarios"
UI_HERO_BADGE_NONPROFIT_TITLE = "Sin fines de lucro"
UI_HERO_BADGE_NONPROFIT_SUB = "Proyecto educativo"
UI_HERO_BADGE_LINUX_TITLE = "Linux First"
UI_HERO_BADGE_LINUX_SUB = "Diseñado para Linux"
UI_HERO_DEV_HEADER = "👥  Desarrolladores"
UI_HERO_LINKS_HEADER = "🔗  Enlaces de interés"
UI_HERO_LINK_GITHUB = "Repositorio en GitHub"
UI_HERO_LINK_DISCORD = "Discord de la Comunidad"
UI_HERO_LINK_WEB = "Página Web Oficial"

UI_TERMS_DLG_TITLE = "Licencia & Términos y Condiciones - CianovaLauncher"
UI_TERMS_DLG_HEADER_TITLE = "Licencia & Términos y Condiciones"
UI_TERMS_DLG_HEADER_SUB = "Documento oficial del repositorio cargado dinámicamente"
UI_TERMS_DLG_ORIGIN = "📄 Origen: Docs/LICENCE & TERMINOS y CONDICIONES.md (Actualizable sin recompilar)"
UI_TERMS_DLG_BTN_OK = "Entendido"
UI_TOOLS_HERO_SUB = "Todo lo que necesitas para personalizar y optimizar tu experiencia de Minecraft Bedrock"


# ── Remaining Dialogs and Tabs Localization ──
UI_INSTALL_SEARCH_PLACEHOLDER = "🔍 Buscar versión (ej. 1.21, 1.20)..."
UI_INSTALL_LOGIN_HINT = "Inicia sesión para continuar"
UI_INSTALL_LOGGED_IN = "Sesión iniciada en: {masked}"
UI_INSTALL_NO_SESSION = "Sin sesión activa"
UI_INSTALL_BTN_LOGIN = "INICIAR SESIÓN"
UI_INSTALL_BTN_SWITCH_ACCOUNT = "CAMBIAR DE CUENTA"
UI_VM_TITLE = "Personalizar Versión"
UI_VM_VERSION_NAME = "Nombre de la Versión:"
UI_VM_BTN_RENAME = "Renombrar"
UI_VM_CUSTOM_ICON = "Icono Personalizado:"
UI_VM_BTN_CHOOSE_IMG = "Seleccionar Imagen"
UI_VM_BTN_RESET = "Restablecer"
UI_VM_ZOOM = "Zoom:"
UI_VM_POS_X = "Pos X:"
UI_VM_POS_Y = "Pos Y:"
UI_VM_SHORTCUTS = "Accesos Directos:"
UI_VM_BTN_CREATE_SC = "Crear Acceso en Escritorio"
UI_VM_BTN_REMOVE_SC = "Quitar Acceso"
UI_VM_MENU_EDIT = "Editar versión"
UI_VM_MENU_BACKUP = "Mover a Respaldo"
UI_VM_MENU_DELETE = "Eliminar"
UI_VM_ICON_RESET_SUCCESS = "Icono restablecido correctamente."
UI_MODS_SUBTITLE = "Administración de librerías nativas y catálogo en línea"
UI_MODS_TAB_INSTALLED = "Instalados"
UI_MODS_TAB_DOWNLOAD = "Descargar"
UI_MODS_SEARCH_INSTALLED = "Buscar en mods instalados..."
UI_MODS_SEARCH_DOWNLOAD = "Buscar en catálogo ModDB..."
UI_MODS_BTN_OPEN_FOLDER = "Abrir Carpeta"
UI_MODS_BTN_REFRESH = "Actualizar"
UI_MODS_BTN_IMPORT = "Importar (.so / .zip)"
UI_MODS_BTN_FETCH = "Actualizar catálogo"
UI_MODS_TOOLTIP_OPEN = "Abrir carpeta del mod"
UI_MODS_TOOLTIP_DELETE = "Eliminar mod"
UI_MODS_STATUS_ACTIVE = "Activo"
UI_MODS_STATUS_INACTIVE = "Inactivo"
UI_MODS_DELETE_TITLE = "Eliminar Mod"
UI_MODS_DELETE_CONFIRM = "¿Deseas eliminar permanentemente '{name}'?"
UI_MODS_DELETE_ERROR = "No se pudo eliminar el mod:\n{e}"
UI_MODS_BTN_DOWNLOAD = "Descargar"
UI_MODS_DRM_ACTIVE_TEXT = "Mod DRM oficial (mcpelauncher-updates) instalado y activo para Google Play."
UI_MODS_DRM_DISABLED_TEXT = "Mod DRM desactivado — Se requiere activarlo para iniciar versiones de Google Play."
UI_MODS_DRM_MISSING_TEXT = "Mod DRM no instalado — Necesario para versiones de Google Play (≥ 1.21.30)."
UI_MODS_DRM_ACTIVATE_BTN = "Activar Mod"
UI_MODS_DRM_INSTALL_BTN = "Instalar Mod DRM"
UI_MODS_DRM_DESC = "Mod DRM oficial de mcpelauncher. Requerido para versiones Google Play (≥ 1.21.30). Parchea Pairip Core DRM, libPlayFabMultiplayer y libmaesdk."
UI_MODS_EMPTY_SEARCH = "No hay mods disponibles que coincidan con la búsqueda."
UI_MODS_COUNT_LABEL = "{total_cnt} mod{plural_total} ({active_cnt} activo{plural_active})"
UI_MODS_IMPORT_SUCCESS = "El mod '{bname}' ha sido instalado."
UI_PACKS_TOOLTIP_FOLDER = "Abrir carpeta del pack en el explorador"
UI_PACKS_TOOLTIP_DELETE = "Eliminar pack permanentemente"
UI_PACKS_NO_DESC = "Sin descripción proporcionada."
UI_PACKS_VERSION_LABEL = "Versión: {ver}"
UI_PACKS_VERSION_UNKNOWN = "Versión desconocida"
UI_PACKS_EXPORT_ERROR = "Error de Exportación"
UI_PACKS_DELETE_CONFIRM = "¿Estás seguro de que deseas eliminar permanentemente '{name}'?\n\nEsta acción no se puede deshacer."
UI_PACKS_BTN_OPEN_FOLDER = "Abrir Carpeta"
UI_PACKS_EMPTY_TITLE = "Aún no tienes packs instalados"
UI_PACKS_EMPTY_SUB = "Arrastra archivos .mcpack o .mcaddon directamente aquí, o pulsa en 'Importar Pack'\npara añadir paquetes de texturas o comportamientos a tu juego."
UI_PACKS_BTN_OPEN_PACKS_FOLDER = "Abrir Carpeta de Packs"
UI_PACKS_IMPORT_SUCCESS = "¡El pack '{bname}' ha sido instalado correctamente!"
UI_PACKS_IMPORT_ERROR = "Error de Instalación"
UI_WORLDS_HEADER_TITLE = "GESTIÓN DE MUNDOS"
UI_WORLDS_HEADER_SUB = "Administra, respalda e importa tus mundos de Minecraft Bedrock"
UI_WORLDS_BTN_IMPORT = "Importar Mundo (.mcworld)"
UI_WORLDS_BTN_OPEN_FOLDER = "Abrir Carpeta"
UI_WORLDS_EMPTY_TITLE = "Aún no tienes mundos creados"
UI_WORLDS_EMPTY_SUB = "Crea mundos dentro de Minecraft Bedrock o importa tus respaldos en formato .mcworld.\nTus mundos aparecerán organizados con sus versiones y estadísticas aquí."
UI_WORLDS_BTN_OPEN_WORLDS_FOLDER = "Abrir Carpeta de Mundos"
UI_WORLDS_COUNT_LABEL = "{count} Mundo{plural}"
UI_WORLDS_TOOLTIP_FOLDER = "Abrir carpeta del mundo en el explorador de archivos"
UI_WORLDS_TOOLTIP_EXPORT = "Exportar mundo a archivo .mcworld..."
UI_WORLDS_TOOLTIP_DELETE = "Eliminar mundo permanentemente"
UI_WORLDS_DELETE_TITLE = "Eliminar Mundo"
UI_WORLDS_DELETE_CONFIRM = "¿Estás seguro de que deseas eliminar permanentemente el mundo '{name}'?\n\nEsta acción no se puede deshacer."
UI_WORLDS_EXPORT_ERROR = "Error de Exportación"
UI_WORLDS_IMPORT_SUCCESS_TITLE = "Mundo Importado"
UI_WORLDS_IMPORT_SUCCESS_MSG = "¡El mundo '{base_name}' ha sido importado con éxito!"
UI_WORLDS_IMPORT_ERROR = "Error de Importación"
UI_SHOTS_HEADER_TITLE = "GALERÍA DE CAPTURAS"
UI_SHOTS_HEADER_SUB = "Visualiza, edita y exporta tus capturas de Minecraft Bedrock"
UI_SHOTS_EMPTY_TITLE = "Aún no tienes capturas de pantalla"
UI_SHOTS_EMPTY_SUB = "Inicia sesión en Minecraft Bedrock con tu cuenta Microsoft y toma capturas desde el menú de pausa in-game.\nTus imágenes aparecerán automáticamente aquí."
UI_SHOTS_BTN_OPEN_FOLDER = "Abrir Carpeta de Capturas"
UI_SHOTS_COUNT_LABEL = "{count} Captura{plural}"
UI_SHOTS_TOOLTIP_COPY = "Copiar imagen al portapapeles"
UI_SHOTS_TOOLTIP_EDIT = "Editar imagen (recorte, rotación, filtros)"
UI_SHOTS_TOOLTIP_SAVE_AS = "Guardar imagen en otra carpeta..."
UI_SHOTS_TOOLTIP_DELETE = "Eliminar captura"
UI_SHOTS_DELETE_TITLE = "Eliminar Captura"
UI_SHOTS_DELETE_CONFIRM = "¿Deseas eliminar permanentemente esta captura de pantalla?"
UI_SHOTS_EDITOR_TITLE = "Editor de Imagen — {name}"
UI_SHOTS_CROP_SECTION = "Recorte y Proporción"
UI_SHOTS_BTN_APPLY_CROP = "Aplicar Recorte"
UI_SHOTS_ROTATION_SECTION = "Rotación"
UI_SHOTS_BTN_SAVE = "Guardar Imagen..."
UI_SHOTS_SAVE_TITLE = "Guardar Captura"
UI_SHOTS_SAVE_ERROR = "Error al Guardar"
UI_SETTINGS_RESET_BG_TOOLTIP = "Eliminar imagen de fondo / Restablecer"

# --- Installation Dialog ---
UI_INSTALL_INVALID_MANIFEST = "Formato de manifiesto inválido"
UI_INSTALL_SELECT_VERSION = "Seleccionar versión"
UI_INSTALL_GOOGLE_TITLE = "Iniciar sesión con Google"
UI_INSTALL_GOOGLE_SUB = "Recuerda que requieres tener Minecraft comprado en Google Play Store."
UI_INSTALL_BTN_REMOVE_ACCOUNT = "Quitar cuenta"
UI_INSTALL_REMOVE_ACCOUNT_TITLE = "Quitar Cuenta"
UI_INSTALL_REMOVE_ACCOUNT_CONFIRM = "¿Estás seguro de que deseas cerrar sesión y quitar la cuenta de Google vinculada?"
UI_FLATPAK_ID_PLACEHOLDER = "Ej: org.cianova.Launcher"
UI_INSTALL_COMPAT_WARN_TITLE = "Aviso de compatibilidad"
UI_INSTALL_COMPAT_WARN_MSG = "Se ha reportado que la versión {version} presenta problemas conocidos:\n\n{warning}\n\nPuedes continuar con la instalación si lo deseas."
UI_INSTALL_LATEST_AUTO = "Última versión (auto) — recomendable"
UI_INSTALL_CANCELING_DOWNLOAD = "Cancelando descarga..."
UI_INSTALL_APK_TITLE = "Archivo APK"
UI_INSTALL_APK_SUB = "Selecciona un archivo APK para instalar"
UI_INSTALL_APK_BTN_CLEAR = "✕ Quitar"
UI_INSTALL_APK_CLEAR_TIP = "Quitar archivo APK seleccionado"
UI_INSTALL_APK_DROP_MAIN = "Arrastra y suelta tu archivo APK aquí"
UI_INSTALL_APK_DROP_SUB = "o selecciona un archivo desde tu dispositivo"
UI_INSTALL_BTN_BROWSE = "Examinar"

# --- DRM Mod & Launch Strings ---
UI_DRM_GOOGLE_REQ_TITLE = "Cuenta de Google Play Requerida"
UI_DRM_GOOGLE_REQ_MSG = "Para descargar e instalar el mod DRM (mcpelauncher-updates) es necesario tener una cuenta de Google Play activa.\n\nPor favor, inicia sesión con tu cuenta de Google Play en la pestaña 'Instalación'."
UI_DRM_UNSUPPORTED_ARCH = "Arquitectura no soportada"
UI_DRM_UNSUPPORTED_ARCH_MOD = "Arquitectura no soportada para este mod: {arch}"
UI_MOD_ALREADY_INSTALLED_REINSTALL = "El mod {mod_name} ya está instalado.\n¿Reinstalar?"
UI_DRM_CANNOT_LAUNCH_MSG = "No se puede iniciar Minecraft Bedrock {version}:\n\nEsta versión fue instalada desde Google Play y requiere obligatoriamente el mod DRM (mcpelauncher-updates) para ejecutarse.\n\nDebes instalar el mod desde la pestaña 'Mods' para poder jugar."
UI_LAUNCH_ERROR_MSG = "Error al iniciar: {error}"

# --- Additional Core UI Actions & Tool Aliases ---
UI_BUTTON_CLOSE_GAME = "Cerrar Juego"
UI_BUTTON_SAVE = "Guardar"

UI_TOOL_TITLE_CONFIG = "Configuración del Juego"
UI_TOOL_DESC_CONFIG = "Edita las opciones y configuración del launcher y del juego."
UI_TOOL_BTN_CONFIG = "Configurar"

UI_TOOL_TITLE_FOLDER = "Carpeta de Datos"
UI_TOOL_DESC_FOLDER = "Accede rápidamente a la carpeta de mundos, configuraciones y más."
UI_TOOL_BTN_FOLDER = "Abrir Carpeta"

UI_TOOL_TITLE_HW = "Analizar Hardware"
UI_TOOL_DESC_HW = "Analiza tu equipo para asegurar un mejor rendimiento."
UI_TOOL_BTN_HW = "Analizar Hardware"
